CREATE INDEX IF NOT EXISTS "chat_user_id_idx" ON "Chat" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_created_at_idx" ON "Chat" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_user_id_idx" ON "Document" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_chat_id_idx" ON "Document" USING btree ("chatId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_visibility_idx" ON "Document" USING btree ("visibility");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_is_current_idx" ON "Document" USING btree ("is_current");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_slug_idx" ON "Document" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_author_idx" ON "Document" USING btree ("author");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_created_at_idx" ON "Document" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_updated_at_idx" ON "Document" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_user_visibility_idx" ON "Document" USING btree ("userId","visibility");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_version_document_id_idx" ON "DocumentVersion" USING btree ("documentId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_version_version_idx" ON "DocumentVersion" USING btree ("version");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_version_previous_version_id_idx" ON "DocumentVersion" USING btree ("previous_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_version_created_at_idx" ON "DocumentVersion" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_version_document_version_idx" ON "DocumentVersion" USING btree ("documentId","version");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_chat_id_idx" ON "Message" USING btree ("chatId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_created_at_idx" ON "Message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_role_idx" ON "Message" USING btree ("role");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_provider_user_id_idx" ON "account" USING btree ("provider_id","user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_expires_at_idx" ON "account" USING btree ("access_token_expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_reference_id_idx" ON "subscription" USING btree ("reference_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_status_idx" ON "subscription" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_stripe_customer_id_idx" ON "subscription" USING btree ("stripe_customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_period_end_idx" ON "subscription" USING btree ("period_end");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_trial_end_idx" ON "subscription" USING btree ("trial_end");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_created_at_idx" ON "subscription" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_email_idx" ON "user" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_username_idx" ON "user" USING btree ("username");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_stripe_customer_id_idx" ON "user" USING btree ("stripe_customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_created_at_idx" ON "user" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_updated_at_idx" ON "user" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_email_verified_idx" ON "user" USING btree ("email_verified");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "verification_expires_at_idx" ON "verification" USING btree ("expires_at");